### PR TITLE
[refactor] simplify Source Code by adding File & Message models

### PR DESCRIPTION
**Pull request by TechQuery**
1. [refactor] simplify Source Code by adding File & Message models
2. [add] Global Error toast
3. [migrate] replace Vite with Parcel to enable ES Decorator stage-3
4. [optimize] format Source Code

### CODE REVIEW

**Comment by stevending1st** [comment]
@TechQuery This is a break change🥲

**Comment by stevending1st** [comment]
@TechQuery change the  Action file please： 
https://github.com/kaiyuanshe/lark-base-plugin-batch-upload-file/blob/52ea6d98f1a17c7240fbeb5b01546109a3673121/.github/workflows/deploy.yml#L24-L36

**Comment by TechQuery** [comment]
> @TechQuery This is a break change🥲

Refactor is not break.

**Comment by TechQuery** [comment]
> @TechQuery change the  Action file please： 
> https://github.com/kaiyuanshe/lark-base-plugin-batch-upload-file/blob/52ea6d98f1a17c7240fbeb5b01546109a3673121/.github/workflows/deploy.yml#L24-L36

There is nothing to change: same `build` command & `dist` folder.

**Comment by stevending1st** [comment]
> Refactor is not break.

Action was break 🥲

https://github.com/kaiyuanshe/lark-base-plugin-batch-upload-file/actions/runs/11542155856/job/32125033895

**Comment by TechQuery** [comment]
> > Refactor is not break.
> 
> Action was break 🥲
> 
> https://github.com/kaiyuanshe/lark-base-plugin-batch-upload-file/actions/runs/11542155856/job/32125033895

Fixed in 435d378 , I didn't find this Building Configuration bug without offline Git hooks or online CI/CD.

**Comment by stevending1st** [comment]
> Fixed in [435d378](https://github.com/kaiyuanshe/lark-base-plugin-batch-upload-file/commit/435d378916ce6eb92035ef57a936969ad4da365b) , I didn't find this Building Configuration bug without offline Git hooks or online CI/CD.

thx

**Pull request merged**
